services:
  web:
    build: .
    command: gunicorn petcare.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - default

  nginx:
    image: nginx:1.25-alpine
    container_name: petcare_nginx
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - web
    networks:
      - default
    restart: always

  redis:
    image: "redis:7-alpine"
    volumes:
      - redis_data:/data
    networks:
      - default

  celery_worker:
    build: .
    command: celery -A petcare worker -l info
    restart: unless-stopped
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - default

  celery_beat:
    build: .
    command: celery -A petcare beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - default

volumes:
  redis_data:
  staticfiles:
  media_volume:

networks:
  default:
    name: gateway_net
    external: true
